# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestScrollclickmore():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_scrollclickmore(self):
    self.driver.get("https://www.ap7.se//vart-utbud/ap7-aktiefond/")
    self.driver.set_window_size(1427, 800)
    self.driver.find_element(By.CSS_SELECTOR, ".ap7__fundListingShowAll").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".ap7__fundListingShowAll")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
  
